# Spreadsheet settings
# Worksheet name
# spreadsheet: FALA_test
spreadsheet: 新着論文レビュー MasterFile
# target worksheet number (0 start)

wks:
  first:
    num: 0
    id: FA_ID
    template: fa_detail.html
    menu_template: menulist_base.html
    require: ['Title', 'FA_URL', 'Date']
    static_file: fa_contants.json
    summary_file: fa_summary.json
    file_name_column: FA_ID
    file_path: https://dbarchive.biosciencedbc.jp/data/first_authors/data/
    img_path: https://dbarchive.biosciencedbc.jp/data/first_authors/data/Fig/
    bucket: fa.bmu.jp
    # bucket_profileはサーバーごとaws configure --profileで設定した値
    bucket_profile: fa-bmu-jp
    # 追加してレンダリングするspreadsheetの項目
    # extra: post_content_extra


# Google API Key file
# 本番環境
jsonkey: conf/FirstAuthor-30b6c7309175.json
# Column name for item id
id: date
# Column name for filename
# filenameはFA_URLをsplitして生成する
filename: date

# Directory settings
static_list_path: contents
#output_path: /var/www/fa/
output_path: html/
template_path: template
tag_path: html/js/
# riot.tag path
module_path: html/js/


# Common Template
# リストなど共有するテンプレートの記述が必要であればこのセクションを残す
template:
  picture_gallery: sub_picture_gallery.html
  picture_list: sub_picture_list.html

# FA keywords annotation
annotation:
  wks:
    num: 4
  class: anno
  repl_count: 1
  flag: 削除候補フラグ


